allow_remote_control yes
listen_on unix:/tmp/mykitty

font_family IosevkaTermNFM
font_features IosevkaTermNFM -calt -liga -dlig
font_size 16.0
modify_font baseline 5
modify_font cell_height -8px
text_composition_strategy legacy

initial_window_height 40c
initial_window_width 130c
remember_window_position yes
remember_window_size no
startup_session startup.kitty-session
window_margin_width 3

macos_colorspace displayp3
macos_option_as_alt yes
macos_quit_when_last_window_closed yes

shell_integration no-title

active_tab_font_style normal
inactive_tab_font_style normal
tab_bar_filter session:~ or session:^$
tab_bar_margin_height 3 0
tab_bar_margin_width 3
tab_bar_style separator
tab_separator " "

kitty_mod super
map kitty_mod+[ previous_tab
map kitty_mod+] next_tab
map kitty_mod+d close_window
map kitty_mod+enter new_window_with_cwd
map kitty_mod+g goto_session
map kitty_mod+n new_os_window_with_cwd
map kitty_mod+t new_tab_with_cwd

scrollback_lines 20000
