allow_remote_control yes

font_family IosevkaTermNFM
font_features IosevkaTermNFM -calt -liga -dlig
font_size 16.0

macos_colorspace displayp3
macos_option_as_alt yes
macos_quit_when_last_window_closed yes

modify_font baseline 5
modify_font cell_height -8px

text_composition_strategy legacy

window_margin_width 4 0 0 4
