modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      Ctrl_L: CapsLock

keymap:
  - name: Firefox (vim like navigation)
    application:
      only: firefox
    remap:
      Ctrl-h: Left
      Ctrl-l: Right
      Ctrl-k: Up
      Ctrl-j: Down
      Ctrl-p: Up
      Ctrl-n: Down
