background #161618
foreground #cacac2
selection_background #545450
selection_foreground #dddddd
cursor #d4a943
cursor_text_color #0e0e0e

active_tab_foreground #cacac2
active_tab_background #161618
inactive_tab_foreground #444444
inactive_tab_background #161618

color0 #131314
color1 #b38f8f
color2 #a3be8c
color3 #ebcb8b
color4 #6c7a8a
color5 #b3a3d3
color6 #6ac6f2
color7 #dddddd
color8 #444444
color9 #d9a6a6
color10 #c3de9c
color11 #fbe4a8
color12 #8fa3b3
color13 #d3a3d3
color14 #8ac6f2
color15 #ffffff
